'use client';

import React from 'react';
import { motion } from 'framer-motion';
import {
  CheckCircle,
  Sunrise,
  Sun,
  Moon,
  AlertOctagon,
  DollarSign,
  HelpCircle,
  Undo2,
  AlertTriangle,
  Sparkles,
  ArrowRight,
  Copy,
  Check,
  Download,
  Printer
} from 'lucide-react';
import { ActionPlanResult } from '../lib/types';
import { useApp } from '../context/AppContext';

interface ActionPlanProps {
  actionPlan: ActionPlanResult;
}

const DAY_GRADIENTS = [
  'linear-gradient(135deg, var(--green-light), var(--green))',
  'linear-gradient(135deg, var(--green-light), var(--wood))',
  'linear-gradient(135deg, var(--wood), var(--earth))',
  'linear-gradient(135deg, var(--green), var(--wood))',
  'linear-gradient(135deg, var(--green-light), var(--earth))',
  'linear-gradient(135deg, var(--wood), var(--green-light))',
  'linear-gradient(135deg, var(--green), var(--earth))',
];

export default function ActionPlan({ actionPlan }: ActionPlanProps) {
  const { resetApp, intake, analysis } = useApp();
  const [copied, setCopied] = React.useState(false);

  const buildFullReport = () => {
    const assumptions = analysis?.assumptions?.map((a, i) =>
      `Assumption ${i+1} [${a.cognitive_bias || 'Bias'}]: ${a.assumption}\nWhy wrong: ${a.why_wrong}\nWhat changes: ${a.what_changes}`
    ).join('\n\n') || '';

    const scenarios = analysis?.scenarios?.map(s =>
      `PATH: ${s.option_name} (${s.confidence}% confidence)\nDay 30: ${s.narrative_30_days}\nDay 60: ${s.narrative_60_days}\nDay 90: ${s.narrative_90_days}\nHidden cost: ${s.hidden_cost}\nBiggest risk: ${s.biggest_risk}\nWhat you give up: ${s.what_you_give_up}`
    ).join('\n\n---\n\n') || '';

    return `CROSSROADS DECISION REPORT
Generated: ${new Date().toLocaleDateString()}
=====================================

DECISION: ${intake?.decision || ''}

HIDDEN ASSUMPTIONS IDENTIFIED:
${assumptions}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SCENARIO PROJECTIONS:
${scenarios}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

YOUR 7-DAY ACTION PLAN: "${actionPlan.chosen_path}"
${actionPlan.plan.map(d => `DAY ${d.day} (${d.time_of_day})${!d.reversible ? ' ⚠️ IRREVERSIBLE' : ''}${d.costs_money ? ' 💰 COSTS MONEY' : ''}\n→ ${d.action}\n   Why: ${d.why_first}`).join('\n\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DAY 7 REFLECTION: ${actionPlan.reflection_prompt}
FALLBACK PLAN: ${actionPlan.fallback}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Crossroads · The choice is always yours.
`;
  };

  const handleDownload = () => {
    const text = buildFullReport();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `crossroads-decision-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyPlan = async () => {
    const planText = `📋 MY 7-DAY ACTION PLAN: "${actionPlan.chosen_path}"
Generated by Crossroads — AI Decision Simulator
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${actionPlan.plan.map(d => `DAY ${d.day} (${d.time_of_day})${!d.reversible ? ' ⚠️ IRREVERSIBLE' : ''}${d.costs_money ? ' 💰 COSTS MONEY' : ''}
→ ${d.action}
   Why: ${d.why_first}
`).join('\n')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📝 DAY 7 REFLECTION: ${actionPlan.reflection_prompt}

🔄 FALLBACK PLAN: ${actionPlan.fallback}
`;
    try {
      await navigator.clipboard.writeText(planText);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch (e) {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = planText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    }
  };

  const getTimeIcon = (time: 'morning' | 'afternoon' | 'evening') => {
    switch (time) {
      case 'morning':   return <Sunrise className="h-3.5 w-3.5" style={{ color: 'var(--green)' }} />;
      case 'afternoon': return <Sun     className="h-3.5 w-3.5" style={{ color: 'var(--wood)' }} />;
      case 'evening':   return <Moon    className="h-3.5 w-3.5" style={{ color: 'var(--earth)' }} />;
    }
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.12 } },
  };

  const itemVariants = {
    hidden: { opacity: 0, x: -12 },
    show:   { opacity: 1, x: 0 },
  };

  return (
    <div className="mx-auto max-w-3xl space-y-8 pb-12">

      {/* Export / Share bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl px-4 py-3 no-print"
        style={{ background: 'var(--green-dim)', border: '1px solid rgba(34, 90, 61, 0.15)' }}>
        <p className="text-[11px] font-semibold" style={{ color: 'var(--body)' }}>
          Share or download your full decision report.
        </p>
        <div className="flex gap-2 shrink-0">
          <button onClick={handleCopyPlan}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer"
            style={{ background: copied ? 'var(--green-soft)' : '#fff', border: '1px solid var(--border)', color: 'var(--green)' }}>
            {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <button onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer"
            style={{ background: 'var(--green)', border: 'none', color: '#fff' }}>
            <Download className="h-3.5 w-3.5" />
            Download Report
          </button>
          <button onClick={() => window.print()}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer bg-slate-800 border border-slate-700 text-white hover:bg-slate-900">
            <Printer className="h-3.5 w-3.5" />
            Print PDF Report
          </button>
        </div>
      </div>

      {/* Timeline */}
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="relative pl-6 space-y-5 sm:pl-8"
        style={{ borderLeft: '2.5px dashed var(--border)', marginLeft: '20px' }}
      >
        {actionPlan.plan.map((dayPlan, idx) => (
          <motion.div key={dayPlan.day} variants={itemVariants} className="relative">

            {/* Timeline node */}
            <div className="absolute -left-[37px] sm:-left-[47px] top-3 flex h-7 w-7 items-center justify-center rounded-full text-[10px] font-black text-white"
              style={{
                background: DAY_GRADIENTS[idx % DAY_GRADIENTS.length],
                boxShadow: `0 0 12px rgba(34, 90, 61, 0.25)`,
                border: '2px solid var(--canvas)',
              }}>
              {dayPlan.day}
            </div>

            {/* Day card */}
            <div className="glass-sm p-5 transition-all duration-300"
              style={{
                background: '#fdfbf7',
                border: '2px double rgba(10, 60, 47, 0.18)',
              }}>
              {/* Badges row */}
              <div className="flex flex-wrap items-center gap-2 mb-3">
                {/* Time badge */}
                <div className="flex items-center gap-1.5 rounded-md px-2 py-0.5 text-[10px] font-bold capitalize"
                  style={{ background: 'var(--green-soft)', border: '1px solid var(--border-light)', color: 'var(--green)' }}>
                  {getTimeIcon(dayPlan.time_of_day)}
                  <span>{dayPlan.time_of_day}</span>
                </div>

                {dayPlan.reversible ? (
                  <div className="flex items-center gap-1 rounded-md px-2 py-0.5 text-[10px] font-bold"
                    style={{ background: 'var(--green-dim)', border: '1px solid rgba(34, 90, 61, 0.12)', color: 'var(--green)' }}>
                    <Undo2 className="h-3 w-3 shrink-0" />
                    <span>Reversible</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-1 rounded-md px-2 py-0.5 text-[10px] font-bold"
                    style={{ background: 'rgba(155, 34, 38, 0.05)', border: '1px solid rgba(155, 34, 38, 0.15)', color: 'var(--error)' }}>
                    <AlertOctagon className="h-3 w-3 shrink-0" />
                    <span>Irreversible</span>
                  </div>
                )}

                {dayPlan.costs_money && (
                  <div className="flex items-center gap-1 rounded-md px-2 py-0.5 text-[10px] font-bold"
                    style={{ background: 'var(--wood-soft)', border: '1px solid rgba(184, 122, 76, 0.15)', color: 'var(--wood)' }}>
                    <DollarSign className="h-3 w-3 shrink-0" />
                    <span>Requires Budget</span>
                  </div>
                )}
              </div>

              {/* Action text */}
              <p className="text-xs font-bold leading-relaxed" style={{ color: 'var(--ink)' }}>
                {dayPlan.action}
              </p>

              {/* Why first */}
              <div className="mt-3 pt-2.5 text-[10px] font-medium italic leading-relaxed"
                style={{ borderTop: '1px solid var(--border-light)', color: 'var(--muted)' }}>
                <strong style={{ color: 'var(--body)' }}>Why first: </strong>{dayPlan.why_first}
              </div>
            </div>
          </motion.div>
        ))}
      </motion.div>

      {/* Reflection Prompt */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.85, duration: 0.4 }}
        className="rounded-2xl p-5 flex items-start gap-4"
        style={{
          background: 'var(--green-dim)',
          border: '1px solid rgba(34, 90, 61, 0.15)',
          borderLeft: '4px solid var(--green)',
        }}
      >
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl"
          style={{ background: 'var(--green-soft)', border: '1px solid rgba(34, 90, 61, 0.15)' }}>
          <HelpCircle className="h-5 w-5" style={{ color: 'var(--green)' }} />
        </div>
        <div>
          <h4 className="text-[10px] font-black uppercase tracking-wider mb-1.5" style={{ color: 'var(--green)' }}>
            Day 7 Reflection Prompt
          </h4>
          <p className="text-xs font-semibold leading-relaxed" style={{ color: 'var(--body)' }}>
            {actionPlan.reflection_prompt}
          </p>
        </div>
      </motion.div>

      {/* Fallback Plan */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.95, duration: 0.4 }}
        className="rounded-2xl p-5 flex items-start gap-4"
        style={{
          background: 'var(--wood-soft)',
          border: '1px solid rgba(184, 122, 76, 0.15)',
          borderLeft: '4px solid var(--wood)',
        }}
      >
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl"
          style={{ background: 'var(--wood-soft)', border: '1px solid rgba(184, 122, 76, 0.15)' }}>
          <AlertTriangle className="h-5 w-5" style={{ color: 'var(--wood)' }} />
        </div>
        <div>
          <h4 className="text-[10px] font-black uppercase tracking-wider mb-1.5" style={{ color: 'var(--wood)' }}>
            Contingency Fallback Plan
          </h4>
          <p className="text-xs font-semibold leading-relaxed" style={{ color: 'var(--body)' }}>
            {actionPlan.fallback}
          </p>
        </div>
      </motion.div>

      {/* CTA */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1.05 }}
        className="pt-4 text-center"
      >
        <button
          onClick={resetApp}
          className="wood-btn inline-flex text-sm px-8 py-4"
        >
          <Sparkles className="h-4 w-4" />
          <span>Test Another Decision</span>
          <ArrowRight className="h-4 w-4" />
        </button>
      </motion.div>
    </div>
  );
}
